# Generated by Django 4.2.1 on 2024-06-21 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='attempt_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
